### PR TITLE
As fast as morgan

### PR DESCRIPTION
**Pull request by mcollina**
@davidmarkclements please give this a spin :)

### CODE REVIEW

**Comment by davidmarkclements** [comment]
@mcollina ci builds are showing an issue with 0.10 - fails on responsTime test but that may be a coincidence, actually looks like a stream error

**Comment by mcollina** [comment]
@davidmarkclements fixed :). Damn v0.10.

**Comment by davidmarkclements** [comment]
So my results are 

pino: Requests/sec:   6394.63
morgan: Requests/sec:   7981.36
bunyan: Requests/sec:   2440.16
winston: Requests/sec:   5344.15

So an extra 1000 rps over winston, and almost 4000rps more than bunyan, 
but morgan is still ahead by around 1500rps. Still, would be v. happy with this 
since morgan is an apple vs oranges comparison anyway

**Comment by davidmarkclements** [comment]
my bad I hadn't set production flag it's actually faster than morgan:

pino: Requests/sec:   8116.35
morgan: Requests/sec:   7834.94

how come we're only doing the cork/uncork in prod?

**Comment by davidmarkclements** [comment]
Yeah I can't get any more speed out of this, the only suggestion I would make is putting the stream.cork check outside of the interval, e.g:

```js
  if (isProduction && stream.cork) {
    // increase speed by 20% by chunking writes
    loggingMiddleware.interval = setInterval(function () {
        stream.uncork()
        stream.cork()
    }, 100)
    loggingMiddleware.interval.unref()
  }
```

It doesn't make a perceptible difference to perf, but at the same time if we can avoid checking a prop every 100ms we should

**Comment by davidmarkclements** [comment]
btw I'm not seeing any perf difference when removing the cork/uncork code - not on 5.10 nor on 4.2.3

**Comment by mcollina** [comment]
Because we don't have access to the server. When it closes, you need to
clear the interval. In unit test, this is really bad. In dev, having a
100ms delay might complicate debugging slightly.

We might also want to uncork() before exit..

Also we should support corking the stream via options as well.

Il giorno lun 4 apr 2016 alle 14:28 David Mark Clements <
notifications@github.com> ha scritto:

**Comment by davidmarkclements** [comment]
cool - what numbers do we have to prove the cork/uncork thing yields a 20% perf increase - I can't replicate any significant variation

**Comment by mcollina** [comment]
I think it was a quirk on my laptop. I'm seeing a 2-5% difference on node v5.8, probably because of my fix  for stream performance on v5.7.

> my bad I hadn't set production flag it's actually faster than morgan:
pino: Requests/sec: 8116.35
morgan: Requests/sec: 7834.94

I'm missing the point here, the only difference in pino is the cork/uncork thing.

**Comment by mcollina** [comment]
@davidmarkclements should I just remove cork/uncork?

**Comment by davidmarkclements** [comment]
...yeah i think so

**Comment by mcollina** [comment]
Done. Good for merging?

**Comment by davidmarkclements** [comment]
Good to go

**Pull request merged**
